"""empty message

Revision ID: 028c762ec2a4
Revises: None
Create Date: 2017-02-28 23:59:31.008062

"""

# revision identifiers, used by Alembic.
revision = '028c762ec2a4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', 'COMPLETED'), nullable=True))
    op.add_column('group', sa.Column('profile_image_id', sa.Integer(), nullable=True))
    op.drop_column('group', 'profileImage')
    op.drop_column('group', 'profileImageId')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('profileImageId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('profileImage', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('group', 'profile_image_id')
    op.drop_column('bucket', 'status')
    ### end Alembic commands ###
