"""empty message

Revision ID: 28667ea7d2ba
Revises: 9aa8b3ceb041
Create Date: 2016-08-08 17:41:48.578221

"""

# revision identifiers, used by Alembic.
revision = '28667ea7d2ba'
down_revision = '9aa8b3ceb041'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complete_bucket', sa.Column('complete_day', sa.Integer(), nullable=True))
    op.add_column('complete_bucket', sa.Column('complete_month', sa.Integer(), nullable=True))
    op.add_column('complete_bucket', sa.Column('complete_year', sa.Integer(), nullable=True))
    op.drop_column('complete_bucket', 'completedate')
    op.add_column('uncomplete_bucket', sa.Column('when_day', sa.Integer(), nullable=True))
    op.add_column('uncomplete_bucket', sa.Column('when_year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uncomplete_bucket', 'when_year')
    op.drop_column('uncomplete_bucket', 'when_day')
    op.add_column('complete_bucket', sa.Column('completedate', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('complete_bucket', 'complete_year')
    op.drop_column('complete_bucket', 'complete_month')
    op.drop_column('complete_bucket', 'complete_day')
    ### end Alembic commands ###
