"""empty message

Revision ID: 42a51078d588
Revises: 4409ef016bce
Create Date: 2016-08-03 23:24:48.295676

"""

# revision identifiers, used by Alembic.
revision = '42a51078d588'
down_revision = '4409ef016bce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complete_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucketid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketid'], ['uncomplete_bucket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complete_bucket')
    ### end Alembic commands ###
