"""empty message

Revision ID: 4409ef016bce
Revises: 4f28717220b2
Create Date: 2016-08-03 23:20:48.098300

"""

# revision identifiers, used by Alembic.
revision = '4409ef016bce'
down_revision = '4f28717220b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uncomplete_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('when_month', sa.Integer(), nullable=True),
    sa.Column('where', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('reward', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('iscomplete', sa.Boolean(), nullable=True),
    sa.Column('excesslimit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uncomplete_bucket')
    ### end Alembic commands ###
