"""empty message

Revision ID: 4647e0bf528b
Revises: bd97cff1e3cf
Create Date: 2017-03-20 19:42:41.098269

"""

# revision identifiers, used by Alembic.
revision = '4647e0bf528b'
down_revision = 'bd97cff1e3cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('complete_message_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucket', 'user', ['complete_message_user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket', type_='foreignkey')
    op.drop_column('bucket', 'complete_message_user_id')
    ### end Alembic commands ###
