"""empty message

Revision ID: 49062719bab7
Revises: 4647e0bf528b
Create Date: 2017-03-20 21:05:18.563425

"""

# revision identifiers, used by Alembic.
revision = '49062719bab7'
down_revision = '4647e0bf528b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('complete_date', sa.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'complete_date')
    ### end Alembic commands ###
