"""empty message

Revision ID: 4f28717220b2
Revises: 2bb38328b6aa
Create Date: 2016-07-26 16:32:53.967300

"""

# revision identifiers, used by Alembic.
revision = '4f28717220b2'
down_revision = '2bb38328b6aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photourl', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photourl')
    ### end Alembic commands ###
