"""empty message

Revision ID: 69641cbf8f81
Revises: 706236bb1036
Create Date: 2017-03-14 23:44:08.004433

"""

# revision identifiers, used by Alembic.
revision = '69641cbf8f81'
down_revision = '706236bb1036'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('complete_message', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'complete_message')
    ### end Alembic commands ###
