"""empty message

Revision ID: 7bfe6371d1dd
Revises: None
Create Date: 2017-03-20 19:34:56.720570

"""

# revision identifiers, used by Alembic.
revision = '7bfe6371d1dd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'complete_time')
    op.drop_column('bucket', 'completed_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('completed_time', mysql.TIMESTAMP(), nullable=True))
    op.add_column('bucket', sa.Column('complete_time', mysql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
