"""empty message

Revision ID: 867b661d2da3
Revises: 28667ea7d2ba
Create Date: 2016-08-08 18:22:10.236426

"""

# revision identifiers, used by Alembic.
revision = '867b661d2da3'
down_revision = '28667ea7d2ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uncomplete_bucket', sa.Column('limit_day', sa.Integer(), nullable=True))
    op.add_column('uncomplete_bucket', sa.Column('limit_month', sa.Integer(), nullable=True))
    op.add_column('uncomplete_bucket', sa.Column('limit_year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uncomplete_bucket', 'limit_year')
    op.drop_column('uncomplete_bucket', 'limit_month')
    op.drop_column('uncomplete_bucket', 'limit_day')
    ### end Alembic commands ###
