"""empty message

Revision ID: 939301384d8a
Revises: 4d1505bfc74d
Create Date: 2017-03-05 00:13:01.947094

"""

# revision identifiers, used by Alembic.
revision = '939301384d8a'
down_revision = '4d1505bfc74d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('title', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'title')
    ### end Alembic commands ###
