"""empty message

Revision ID: ac5555cba75b
Revises: fd0463257ae3
Create Date: 2017-03-23 18:52:10.118568

"""

# revision identifiers, used by Alembic.
revision = 'ac5555cba75b'
down_revision = 'fd0463257ae3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('MALE', 'FEMALE'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    ### end Alembic commands ###
