"""empty message

Revision ID: ba33f1a4938a
Revises: 49062719bab7
Create Date: 2017-03-21 00:41:01.870188

"""

# revision identifiers, used by Alembic.
revision = 'ba33f1a4938a'
down_revision = '49062719bab7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('created', sa.TIMESTAMP(), nullable=True))
    op.add_column('bucket', sa.Column('modified', sa.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'modified')
    op.drop_column('bucket', 'created')
    ### end Alembic commands ###
