"""empty message

Revision ID: bd97cff1e3cf
Revises: 7bfe6371d1dd
Create Date: 2017-03-20 19:37:32.776155

"""

# revision identifiers, used by Alembic.
revision = 'bd97cff1e3cf'
down_revision = '7bfe6371d1dd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'bucket_ibfk_3', 'bucket', type_='foreignkey')
    op.drop_column('bucket', 'complete_message_user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('complete_message_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'bucket_ibfk_3', 'bucket', 'user', ['complete_message_user_id'], ['id'])
    ### end Alembic commands ###
