"""empty message

Revision ID: d0b5dc777eda
Revises: 9d6dcb4faf6e
Create Date: 2017-03-23 23:59:34.523935

"""

# revision identifiers, used by Alembic.
revision = 'd0b5dc777eda'
down_revision = '9d6dcb4faf6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_user_group', sa.Column('created', sa.TIMESTAMP(), nullable=True))
    op.add_column('relation_user_group', sa.Column('modified', sa.TIMESTAMP(), nullable=True))
    op.add_column('relation_user_group', sa.Column('status', sa.Enum('REQUEST', 'ACCEPTED', 'REJECTED'), nullable=True))
    op.drop_column('relation_user_group', 'edited_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_user_group', sa.Column('edited_time', mysql.DATETIME(), nullable=True))
    op.drop_column('relation_user_group', 'status')
    op.drop_column('relation_user_group', 'modified')
    op.drop_column('relation_user_group', 'created')
    ### end Alembic commands ###
