"""empty message

Revision ID: e04a48bb1bc5
Revises: 939301384d8a
Create Date: 2017-03-11 19:37:56.396303

"""

# revision identifiers, used by Alembic.
revision = 'e04a48bb1bc5'
down_revision = '939301384d8a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'complete_message')
    op.drop_column('bucket', 'reply_message')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('reply_message', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('bucket', sa.Column('complete_message', mysql.VARCHAR(length=1000), nullable=True))
    ### end Alembic commands ###
