"""empty message

Revision ID: fd0463257ae3
Revises: ba33f1a4938a
Create Date: 2017-03-21 18:32:08.038567

"""

# revision identifiers, used by Alembic.
revision = 'fd0463257ae3'
down_revision = 'ba33f1a4938a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###
